version: 2
updates:
    -   package-ecosystem: composer
        directory: /
        target-branch: main
        open-pull-requests-limit: 20
        labels:
            - 'dependencies'
            - 'php'
        schedule:
            interval: daily

    -   package-ecosystem: npm
        directory: /
        target-branch: main
        open-pull-requests-limit: 20
        labels:
            - 'dependencies'
            - 'js'
        schedule:
            interval: daily
