framework:
    csrf_protection: true
    http_method_override: false
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: true
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
