liip_imagine:
    driver: gd
    messenger: true

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: cache

    filter_sets:
        thumbnail_1200x1200: # OpenGraph images
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [ 1200, 1200 ], mode: outbound }
                background: { size: [ 1200, 1200 ], position: center, color: '#212529' }

        thumbnail_1400x800: # Carousel slides
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [ 1400, 800 ], mode: outbound }
                background: { size: [ 1400, 800 ], position: center, color: '#212529' }

        thumbnail_560x320: # Card thumbnails
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [ 560, 320 ], mode: outbound }
                background: { size: [ 560, 320 ], position: center, color: '#212529' }

        thumbnail_280x160: # Search result thumbnails
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [ 280, 160 ], mode: outbound }
                background: { size: [ 280, 160 ], position: center, color: '#212529' }
