framework:
    mailer:
        dsn: '%env(resolve:MAILER_DSN)%'

        envelope:
            sender: 'noreply@aircraft-database.com'

        headers:
            From: 'Aircraft database <noreply@aircraft-database.com>'
            Reply-To: 'Aircraft database <contact@aircraft-database.com>'
