babdev_pagerfanta:
    default_view: custom

services:
    _defaults:
        autowire: true
        autoconfigure: true

    pagerfanta.view.custom:
        class: Pagerfanta\View\OptionableView
        arguments:
            - '@pagerfanta.view.twitter_bootstrap5'
            - { proximity: 2,
                prev_message: '<span class="fal fa-angle-left" aria-hidden="true"></span>',
                next_message: '<span class="fal fa-angle-right" aria-hidden="true"></span>' }
        tags:
            - { name: pagerfanta.view, alias: custom }
