parameters:
    sitemap.directory: 'sitemap'

presta_sitemap:
    default_section: default
    dumper: App\Service\SitemapDumper
    dump_directory: '%kernel.project_dir%/public/%sitemap.directory%'

    defaults:
        changefreq: ~
        lastmod: now
        priority: ~
