security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: argon2id
            memory_cost: 8192
            time_cost: 16

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: user_provider
            user_checker: App\Security\UserChecker
            custom_authenticators:
                - App\Security\Authenticator\GoogleAuthenticator

            form_login:
                login_path: security_login
                check_path: security_login
                username_parameter: login[email]
                password_parameter: login[password]

            logout:
                path: security_logout

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/downloads/, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }

when@prod:
    security:
        firewalls:
            main:
                login_throttling:
                    max_attempts: 3
                    interval: 15 minutes

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: argon2id
                memory_cost: 10
                time_cost: 3
