parameters:
    env(COMPOSER_JSON): '%kernel.project_dir%/composer.json'

sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false

    messenger:
        enabled: true
        capture_soft_fails: true

    options:
        traces_sampler: sentry.callback.traces_sampler
        release: 'aircraft-database@%env(key:version:json:file:COMPOSER_JSON)%'
        send_default_pii: true

services:
    sentry.callback.traces_sampler:
        class: App\Service\Sentry
        factory: [ '@App\Service\Sentry', getTracesSampler ]
