parameters:
    env(COMPOSER_JSON): '%kernel.project_dir%/composer.json'
    sentry.sample_rate: 1.0
    sentry.traces_sample_rate: 0.025

sentry:
    dsn: '%env(resolve:SENTRY_DSN)%'
    register_error_listener: false

    messenger:
        enabled: true
        capture_soft_fails: true

    options:
        release: 'aircraft-database@%env(key:version:json:file:COMPOSER_JSON)%'
        sample_rate: '%sentry.sample_rate%'
        send_default_pii: true
        traces_sample_rate: '%sentry.traces_sample_rate%'

twig:
    globals:
        sentry:
            dsn: '%env(resolve:SENTRY_DSN)%'
            release: 'aircraft-database@%env(key:version:json:file:COMPOSER_JSON)%'
            sampleRate: '%sentry.sample_rate%'
            traceSampleRate: '%sentry.traces_sample_rate%'
