twig:
    default_path: '%kernel.project_dir%/templates'
    strict_variables: '%kernel.debug%'

    form_themes:
        - bootstrap_5_layout.html.twig
        - form.html.twig

    globals:
        site:
            description: Global database of aircraft and engine models.
            title: Aircraft database
