webpack_encore:
    output_path: '%kernel.project_dir%/public/assets'
    crossorigin: anonymous
    preload: true

    script_attributes:
        defer: true
        referrerpolicy: origin

    link_attributes:
        referrerpolicy: origin

when@prod:
    webpack_encore:
        cache: true

when@test:
    webpack_encore:
        strict_mode: false
