webpack_encore:
    crossorigin: anonymous
    output_path: '%kernel.project_dir%/public/assets'
    preload: true

    link_attributes:
        async: true

    script_attributes:
        defer: true

when@prod:
    webpack_encore:
        cache: true

when@test:
    webpack_encore:
        strict_mode: false
