version: '3.8'

services:
    mysql:
        image: aircraft-database/mysql:8.0
        build: docker/mysql
        container_name: aircraft-database-mysql
        environment:
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            -   type: volume
                source: mysql-data
                target: /var/lib/mysql
        networks:
            internal:
                ipv4_address: 172.8.1.2

    nginx:
        image: aircraft-database/nginx:1.21
        build: docker/nginx
        container_name: aircraft-database-nginx
        working_dir: /usr/share/nginx/html
        volumes:
            -   type: bind
                source: .
                target: /usr/share/nginx/html
        networks:
            internal:
                ipv4_address: 172.8.1.3

    node:
        image: aircraft-database/node:17.7
        build: docker/node
        container_name: aircraft-database-node
        working_dir: /usr/share/nginx/html
        volumes:
            -   type: bind
                source: .
                target: /usr/share/nginx/html
        networks:
            internal:
                ipv4_address: 172.8.1.4

    php:
        image: aircraft-database/php:8.1
        build: docker/php
        container_name: aircraft-database-php
        working_dir: /usr/share/nginx/html
        volumes:
            -   type: bind
                source: .
                target: /usr/share/nginx/html
        networks:
            internal:
                ipv4_address: 172.8.1.5
        extra_hosts:
            - 'mysql: 172.8.1.2'
            - 'rabbitmq: 172.8.1.7'
            - 'redis: 172.8.1.8'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.1
        container_name: aircraft-database-phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        networks:
            internal:
                ipv4_address: 172.8.1.6

    rabbitmq:
        image: aircraft-database/rabbitmq:3.9
        build: docker/rabbitmq
        container_name: aircraft-database-rabbitmq
        networks:
            internal:
                ipv4_address: 172.8.1.7

    redis:
        image: redis:6.2
        container_name: aircraft-database-redis
        volumes:
            -   type: volume
                source: redis-data
                target: /data
        networks:
            internal:
                ipv4_address: 172.8.1.8

networks:
    internal:
        name: aircraft-database
        ipam:
            driver: default
            config:
                -   subnet: 172.8.1.0/24

volumes:
    mysql-data:
    redis-data:
