version: '3.8'

services:
    mysql:
        ports:
            - '3306:3306'

    nginx:
        ports:
            - '80:80'
            - '443:443'

    phpmyadmin:
        ports:
            - '3307:80'
