version: '3.8'

services:
    mailer:
        image: schickling/mailcatcher
        container_name: aircraft-database-mailer
        networks:
            internal:
                ipv4_address: 172.16.0.2

    mysql:
        image: aircraft-database/mysql:8.0
        build: docker/mysql
        container_name: aircraft-database-mysql
        environment:
            MYSQL_DATABASE: db_name
            MYSQL_PASSWORD: db_password
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: db_user
        volumes:
            -   type: volume
                source: mysql-data
                target: /var/lib/mysql
        networks:
            internal:
                ipv4_address: 172.16.0.3

    nginx:
        image: aircraft-database/nginx:1.21
        build: docker/nginx
        container_name: aircraft-database-nginx
        working_dir: /usr/share/nginx/html
        volumes:
            -   type: bind
                source: .
                target: /usr/share/nginx/html
        networks:
            internal:
                ipv4_address: 172.16.0.4

    node:
        image: aircraft-database/node:16.15
        build: docker/node
        container_name: aircraft-database-node
        working_dir: /usr/share/nginx/html
        volumes:
            -   type: bind
                source: .
                target: /usr/share/nginx/html
        networks:
            internal:
                ipv4_address: 172.16.0.5

    php:
        image: aircraft-database/php:8.1
        build: docker/php
        container_name: aircraft-database-php
        working_dir: /usr/share/nginx/html
        volumes:
            -   type: bind
                source: .
                target: /usr/share/nginx/html
        networks:
            internal:
                ipv4_address: 172.16.0.6
        extra_hosts:
            - 'mailer: 172.16.0.2'
            - 'mysql: 172.16.0.3'
            - 'rabbitmq: 172.16.0.9'
            - 'redis: 172.16.0.10'

    php-worker:
        image: aircraft-database/php-worker:8.1
        build: docker/php-worker
        container_name: aircraft-database-php-worker
        working_dir: /usr/share/nginx/html
        volumes:
            -   type: bind
                source: .
                target: /usr/share/nginx/html
        networks:
            internal:
                ipv4_address: 172.16.0.7
        extra_hosts:
            - 'mailer: 172.16.0.2'
            - 'mysql: 172.16.0.3'
            - 'rabbitmq: 172.16.0.9'
            - 'redis: 172.16.0.10'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2
        container_name: aircraft-database-phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PASSWORD: root
            PMA_USER: root
        networks:
            internal:
                ipv4_address: 172.16.0.8

    rabbitmq:
        image: aircraft-database/rabbitmq:3.10
        build: docker/rabbitmq
        container_name: aircraft-database-rabbitmq
        volumes:
            -   type: volume
                source: rabbitmq-data
                target: /var/lib/rabbitmq
        networks:
            internal:
                ipv4_address: 172.16.0.9

    redis:
        image: redis:7.0
        container_name: aircraft-database-redis
        volumes:
            -   type: volume
                source: redis-data
                target: /data
        networks:
            internal:
                ipv4_address: 172.16.0.10

networks:
    internal:
        name: aircraft-database
        ipam:
            driver: default
            config:
                -   subnet: 172.16.0.0/24

volumes:
    mysql-data:
    rabbitmq-data:
    redis-data:
