name: Node

on: [ push, pull_request ]

jobs:
    lint-scripts:
        name: Lint scripts
        runs-on: ubuntu-latest
        env:
            FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '16.15'

            -   name: Get npm cache directory
                id: npm-cache-dir
                run: echo "::set-output name=dir::$(npm get cache)"

            -   name: Cache dependencies
                id: npm-cache
                uses: actions/cache@v2
                with:
                    path: ${{ steps.npm-cache-dir.outputs.dir }}
                    key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: ${{ runner.os }}-npm-

            -   name: Install dependencies
                run: npm install

            -   name: Lint scripts
                run: npm run lint:scripts

    lint-styles:
        name: Lint styles
        runs-on: ubuntu-latest
        env:
            FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '18.2'

            -   name: Get npm cache directory
                id: npm-cache-dir
                run: echo "::set-output name=dir::$(npm get cache)"

            -   name: Cache dependencies
                id: npm-cache
                uses: actions/cache@v2
                with:
                    path: ${{ steps.npm-cache-dir.outputs.dir }}
                    key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: ${{ runner.os }}-npm-

            -   name: Install dependencies
                run: npm install

            -   name: Lint styles
                run: npm run lint:styles
