name: Node.js

on: [ push, pull_request ]

jobs:
    nodejs:
        name: Node.js
        runs-on: ubuntu-latest
        env:
            FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '17.1'

            - name: Get npm cache directory
              id: npm-cache-dir
              run: |
                echo "::set-output name=dir::$(npm get cache)"

            - name: Cache dependencies
              id: npm-cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                    ${{ runner.os }}-npm-

            - name: Install dependencies
              run: npm install

            - name: Lint scripts
              run: npm run lint:scripts

            - name: Lint stylesheets
              run: npm run lint:styles
