name: PHP

on: [ push, pull_request ]

jobs:
    php:
        name: PHP
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  tools: pecl
                  extensions: amqp, bcmath, gd, gmp, intl, pdo, pdo_mysql, redis, sysvsem, uuid, xsl, zip
                  ini-values: memory_limit=1G

            - name: Get Composer cache directory
              id: composer-cache-dir
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                    ${{ runner.os }}-composer-

            - name: Validate composer.json
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run PHPStan
              run: composer run phpstan
